services:
  core:
    build: .
    ports:
      - "8080:8080"
  mongo:
    image: "mongo:latest"
  vault:
    image: "hashicorp/vault:latest"
  keycloak:
    image: "keycloak/keycloak:latest"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    command: ["start-dev"]