FROM eclipse-temurin:21-jre
MAINTAINER DevTeam45

RUN mkdir -p /config

# MongoDB
ARG MONGO_HOST
ARG MONGO_PORT
ARG MONGO_INITDB_DATABASE
ARG MONGO_INITDB_ROOT_USERNAME
ARG MONGO_INITDB_ROOT_PASSWORD

COPY target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar"]
