FROM alpine:latest AS builder
MAINTAINER DevTeam45

# install openssl
RUN apk add --no-cache bash
RUN apk add --no-cache openssl

# copy script
COPY generate_secrets.sh /usr/local/bin/generate_secrets.sh
RUN chmod +x /usr/local/bin/generate_secrets.sh

# start script
CMD ["/usr/local/bin/generate_secrets.sh"]
# CMD ["tail", "-f", "/dev/null"] #debugging