/*
 * eLabFTW REST API v2 Documentation
 * This document describes all available endpoints and methods for eLabFTW's API version 2. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.io.IOException;
/**
 * Event
 */

@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-15T12:02:45.960786319Z[GMT]")

public class Event {
  @SerializedName("title")
  private String title = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("start")
  private String start = null;

  @SerializedName("end")
  private String end = null;

  @SerializedName("userid")
  private Integer userid = null;

  @SerializedName("item_title")
  private String itemTitle = null;

  @SerializedName("color")
  private String color = null;

  @SerializedName("fullname")
  private String fullname = null;

  @SerializedName("item_link")
  private Integer itemLink = null;

  @SerializedName("item_link_title")
  private String itemLinkTitle = null;

  @SerializedName("experiment")
  private Integer experiment = null;

  @SerializedName("experiment_title")
  private String experimentTitle = null;

  public Event title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Event id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Event start(String start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @Schema(description = "")
  public String getStart() {
    return start;
  }

  public void setStart(String start) {
    this.start = start;
  }

  public Event end(String end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @Schema(description = "")
  public String getEnd() {
    return end;
  }

  public void setEnd(String end) {
    this.end = end;
  }

  public Event userid(Integer userid) {
    this.userid = userid;
    return this;
  }

   /**
   * Get userid
   * @return userid
  **/
  @Schema(description = "")
  public Integer getUserid() {
    return userid;
  }

  public void setUserid(Integer userid) {
    this.userid = userid;
  }

  public Event itemTitle(String itemTitle) {
    this.itemTitle = itemTitle;
    return this;
  }

   /**
   * Get itemTitle
   * @return itemTitle
  **/
  @Schema(description = "")
  public String getItemTitle() {
    return itemTitle;
  }

  public void setItemTitle(String itemTitle) {
    this.itemTitle = itemTitle;
  }

  public Event color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @Schema(description = "")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public Event fullname(String fullname) {
    this.fullname = fullname;
    return this;
  }

   /**
   * Get fullname
   * @return fullname
  **/
  @Schema(description = "")
  public String getFullname() {
    return fullname;
  }

  public void setFullname(String fullname) {
    this.fullname = fullname;
  }

  public Event itemLink(Integer itemLink) {
    this.itemLink = itemLink;
    return this;
  }

   /**
   * Get itemLink
   * @return itemLink
  **/
  @Schema(description = "")
  public Integer getItemLink() {
    return itemLink;
  }

  public void setItemLink(Integer itemLink) {
    this.itemLink = itemLink;
  }

  public Event itemLinkTitle(String itemLinkTitle) {
    this.itemLinkTitle = itemLinkTitle;
    return this;
  }

   /**
   * Get itemLinkTitle
   * @return itemLinkTitle
  **/
  @Schema(description = "")
  public String getItemLinkTitle() {
    return itemLinkTitle;
  }

  public void setItemLinkTitle(String itemLinkTitle) {
    this.itemLinkTitle = itemLinkTitle;
  }

  public Event experiment(Integer experiment) {
    this.experiment = experiment;
    return this;
  }

   /**
   * Get experiment
   * @return experiment
  **/
  @Schema(description = "")
  public Integer getExperiment() {
    return experiment;
  }

  public void setExperiment(Integer experiment) {
    this.experiment = experiment;
  }

  public Event experimentTitle(String experimentTitle) {
    this.experimentTitle = experimentTitle;
    return this;
  }

   /**
   * Get experimentTitle
   * @return experimentTitle
  **/
  @Schema(description = "")
  public String getExperimentTitle() {
    return experimentTitle;
  }

  public void setExperimentTitle(String experimentTitle) {
    this.experimentTitle = experimentTitle;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Event event = (Event) o;
    return Objects.equals(this.title, event.title) &&
        Objects.equals(this.id, event.id) &&
        Objects.equals(this.start, event.start) &&
        Objects.equals(this.end, event.end) &&
        Objects.equals(this.userid, event.userid) &&
        Objects.equals(this.itemTitle, event.itemTitle) &&
        Objects.equals(this.color, event.color) &&
        Objects.equals(this.fullname, event.fullname) &&
        Objects.equals(this.itemLink, event.itemLink) &&
        Objects.equals(this.itemLinkTitle, event.itemLinkTitle) &&
        Objects.equals(this.experiment, event.experiment) &&
        Objects.equals(this.experimentTitle, event.experimentTitle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, id, start, end, userid, itemTitle, color, fullname, itemLink, itemLinkTitle, experiment, experimentTitle);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    userid: ").append(toIndentedString(userid)).append("\n");
    sb.append("    itemTitle: ").append(toIndentedString(itemTitle)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    fullname: ").append(toIndentedString(fullname)).append("\n");
    sb.append("    itemLink: ").append(toIndentedString(itemLink)).append("\n");
    sb.append("    itemLinkTitle: ").append(toIndentedString(itemLinkTitle)).append("\n");
    sb.append("    experiment: ").append(toIndentedString(experiment)).append("\n");
    sb.append("    experimentTitle: ").append(toIndentedString(experimentTitle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
