/*
 * eLabFTW REST API v2 Documentation
 * This document describes all available endpoints and methods for eLabFTW's API version 2. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * IdExperimentsStatusBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-17T16:14:35.053224103Z[GMT]")

public class IdExperimentsStatusBody {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("color")
  private String color = null;

  @JsonProperty("default")
  private Integer _default = null;

  public IdExperimentsStatusBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Status name
   * @return name
  **/
  @Schema(description = "Status name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IdExperimentsStatusBody color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Hex color without leading \\#. 
   * @return color
  **/
  @Schema(description = "Hex color without leading \\#. ")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public IdExperimentsStatusBody _default(Integer _default) {
    this._default = _default;
    return this;
  }

   /**
   * Is it the default status for the team?
   * @return _default
  **/
  @Schema(description = "Is it the default status for the team?")
  public Integer getDefault() {
    return _default;
  }

  public void setDefault(Integer _default) {
    this._default = _default;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdExperimentsStatusBody idExperimentsStatusBody = (IdExperimentsStatusBody) o;
    return Objects.equals(this.name, idExperimentsStatusBody.name) &&
        Objects.equals(this.color, idExperimentsStatusBody.color) &&
        Objects.equals(this._default, idExperimentsStatusBody._default);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, color, _default);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdExperimentsStatusBody {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
