/*
 * eLabFTW REST API v2 Documentation
 * This document describes all available endpoints and methods for eLabFTW's API version 2. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Idp
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-17T16:14:35.053224103Z[GMT]")

public class Idp {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("entityid")
  private String entityid = null;

  @JsonProperty("sso_url")
  private String ssoUrl = null;

  @JsonProperty("sso_binding")
  private String ssoBinding = null;

  @JsonProperty("slo_url")
  private String sloUrl = null;

  @JsonProperty("slo_binding")
  private String sloBinding = null;

  @JsonProperty("x509")
  private String x509 = null;

  @JsonProperty("x509_new")
  private String x509New = null;

  @JsonProperty("enabled")
  private Integer enabled = null;

  @JsonProperty("email_attr")
  private String emailAttr = null;

  @JsonProperty("team_attr")
  private String teamAttr = null;

  @JsonProperty("fname_attr")
  private String fnameAttr = null;

  @JsonProperty("lname_attr")
  private String lnameAttr = null;

  public Idp id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Idp name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Idp entityid(String entityid) {
    this.entityid = entityid;
    return this;
  }

   /**
   * Get entityid
   * @return entityid
  **/
  @Schema(description = "")
  public String getEntityid() {
    return entityid;
  }

  public void setEntityid(String entityid) {
    this.entityid = entityid;
  }

  public Idp ssoUrl(String ssoUrl) {
    this.ssoUrl = ssoUrl;
    return this;
  }

   /**
   * Get ssoUrl
   * @return ssoUrl
  **/
  @Schema(description = "")
  public String getSsoUrl() {
    return ssoUrl;
  }

  public void setSsoUrl(String ssoUrl) {
    this.ssoUrl = ssoUrl;
  }

  public Idp ssoBinding(String ssoBinding) {
    this.ssoBinding = ssoBinding;
    return this;
  }

   /**
   * Get ssoBinding
   * @return ssoBinding
  **/
  @Schema(description = "")
  public String getSsoBinding() {
    return ssoBinding;
  }

  public void setSsoBinding(String ssoBinding) {
    this.ssoBinding = ssoBinding;
  }

  public Idp sloUrl(String sloUrl) {
    this.sloUrl = sloUrl;
    return this;
  }

   /**
   * Get sloUrl
   * @return sloUrl
  **/
  @Schema(description = "")
  public String getSloUrl() {
    return sloUrl;
  }

  public void setSloUrl(String sloUrl) {
    this.sloUrl = sloUrl;
  }

  public Idp sloBinding(String sloBinding) {
    this.sloBinding = sloBinding;
    return this;
  }

   /**
   * Get sloBinding
   * @return sloBinding
  **/
  @Schema(description = "")
  public String getSloBinding() {
    return sloBinding;
  }

  public void setSloBinding(String sloBinding) {
    this.sloBinding = sloBinding;
  }

  public Idp x509(String x509) {
    this.x509 = x509;
    return this;
  }

   /**
   * Get x509
   * @return x509
  **/
  @Schema(description = "")
  public String getX509() {
    return x509;
  }

  public void setX509(String x509) {
    this.x509 = x509;
  }

  public Idp x509New(String x509New) {
    this.x509New = x509New;
    return this;
  }

   /**
   * Get x509New
   * @return x509New
  **/
  @Schema(description = "")
  public String getX509New() {
    return x509New;
  }

  public void setX509New(String x509New) {
    this.x509New = x509New;
  }

  public Idp enabled(Integer enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @Schema(description = "")
  public Integer getEnabled() {
    return enabled;
  }

  public void setEnabled(Integer enabled) {
    this.enabled = enabled;
  }

  public Idp emailAttr(String emailAttr) {
    this.emailAttr = emailAttr;
    return this;
  }

   /**
   * Get emailAttr
   * @return emailAttr
  **/
  @Schema(description = "")
  public String getEmailAttr() {
    return emailAttr;
  }

  public void setEmailAttr(String emailAttr) {
    this.emailAttr = emailAttr;
  }

  public Idp teamAttr(String teamAttr) {
    this.teamAttr = teamAttr;
    return this;
  }

   /**
   * Get teamAttr
   * @return teamAttr
  **/
  @Schema(description = "")
  public String getTeamAttr() {
    return teamAttr;
  }

  public void setTeamAttr(String teamAttr) {
    this.teamAttr = teamAttr;
  }

  public Idp fnameAttr(String fnameAttr) {
    this.fnameAttr = fnameAttr;
    return this;
  }

   /**
   * Get fnameAttr
   * @return fnameAttr
  **/
  @Schema(description = "")
  public String getFnameAttr() {
    return fnameAttr;
  }

  public void setFnameAttr(String fnameAttr) {
    this.fnameAttr = fnameAttr;
  }

  public Idp lnameAttr(String lnameAttr) {
    this.lnameAttr = lnameAttr;
    return this;
  }

   /**
   * Get lnameAttr
   * @return lnameAttr
  **/
  @Schema(description = "")
  public String getLnameAttr() {
    return lnameAttr;
  }

  public void setLnameAttr(String lnameAttr) {
    this.lnameAttr = lnameAttr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Idp idp = (Idp) o;
    return Objects.equals(this.id, idp.id) &&
        Objects.equals(this.name, idp.name) &&
        Objects.equals(this.entityid, idp.entityid) &&
        Objects.equals(this.ssoUrl, idp.ssoUrl) &&
        Objects.equals(this.ssoBinding, idp.ssoBinding) &&
        Objects.equals(this.sloUrl, idp.sloUrl) &&
        Objects.equals(this.sloBinding, idp.sloBinding) &&
        Objects.equals(this.x509, idp.x509) &&
        Objects.equals(this.x509New, idp.x509New) &&
        Objects.equals(this.enabled, idp.enabled) &&
        Objects.equals(this.emailAttr, idp.emailAttr) &&
        Objects.equals(this.teamAttr, idp.teamAttr) &&
        Objects.equals(this.fnameAttr, idp.fnameAttr) &&
        Objects.equals(this.lnameAttr, idp.lnameAttr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, entityid, ssoUrl, ssoBinding, sloUrl, sloBinding, x509, x509New, enabled, emailAttr, teamAttr, fnameAttr, lnameAttr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Idp {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    entityid: ").append(toIndentedString(entityid)).append("\n");
    sb.append("    ssoUrl: ").append(toIndentedString(ssoUrl)).append("\n");
    sb.append("    ssoBinding: ").append(toIndentedString(ssoBinding)).append("\n");
    sb.append("    sloUrl: ").append(toIndentedString(sloUrl)).append("\n");
    sb.append("    sloBinding: ").append(toIndentedString(sloBinding)).append("\n");
    sb.append("    x509: ").append(toIndentedString(x509)).append("\n");
    sb.append("    x509New: ").append(toIndentedString(x509New)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    emailAttr: ").append(toIndentedString(emailAttr)).append("\n");
    sb.append("    teamAttr: ").append(toIndentedString(teamAttr)).append("\n");
    sb.append("    fnameAttr: ").append(toIndentedString(fnameAttr)).append("\n");
    sb.append("    lnameAttr: ").append(toIndentedString(lnameAttr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
