/*
 * eLabFTW REST API v2 Documentation
 * This document describes all available endpoints and methods for eLabFTW's API version 2. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.io.IOException;
/**
 * ItemsIdBody
 */

@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-15T12:02:45.960786319Z[GMT]")

public class ItemsIdBody {
  @SerializedName("action")
  private String action = "duplicate";

  @SerializedName("copyFiles")
  private Boolean copyFiles = false;

  @SerializedName("linkToOriginal")
  private Boolean linkToOriginal = true;

  public ItemsIdBody action(String action) {
    this.action = action;
    return this;
  }

   /**
   * The \&quot;duplicate\&quot; action creates a new item based from the given item id. 
   * @return action
  **/
  @Schema(description = "The \"duplicate\" action creates a new item based from the given item id. ")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public ItemsIdBody copyFiles(Boolean copyFiles) {
    this.copyFiles = copyFiles;
    return this;
  }

   /**
   * If \&quot;true\&quot;, the action will import the files of the original item. 
   * @return copyFiles
  **/
  @Schema(description = "If \"true\", the action will import the files of the original item. ")
  public Boolean isCopyFiles() {
    return copyFiles;
  }

  public void setCopyFiles(Boolean copyFiles) {
    this.copyFiles = copyFiles;
  }

  public ItemsIdBody linkToOriginal(Boolean linkToOriginal) {
    this.linkToOriginal = linkToOriginal;
    return this;
  }

   /**
   * If \&quot;true\&quot;, the action will create a link to the original item. 
   * @return linkToOriginal
  **/
  @Schema(description = "If \"true\", the action will create a link to the original item. ")
  public Boolean isLinkToOriginal() {
    return linkToOriginal;
  }

  public void setLinkToOriginal(Boolean linkToOriginal) {
    this.linkToOriginal = linkToOriginal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemsIdBody itemsIdBody = (ItemsIdBody) o;
    return Objects.equals(this.action, itemsIdBody.action) &&
        Objects.equals(this.copyFiles, itemsIdBody.copyFiles) &&
        Objects.equals(this.linkToOriginal, itemsIdBody.linkToOriginal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, copyFiles, linkToOriginal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemsIdBody {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    copyFiles: ").append(toIndentedString(copyFiles)).append("\n");
    sb.append("    linkToOriginal: ").append(toIndentedString(linkToOriginal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
