/*
 * eLabFTW REST API v2 Documentation
 * This document describes all available endpoints and methods for eLabFTW's API version 2. 
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Team
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-17T16:14:35.053224103Z[GMT]")

public class Team implements TeamsIdBody {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("common_template")
  private String commonTemplate = null;

  @JsonProperty("common_template_md")
  private String commonTemplateMd = null;

  @JsonProperty("user_create_tag")
  private Integer userCreateTag = null;

  @JsonProperty("force_exp_tpl")
  private Integer forceExpTpl = null;

  @JsonProperty("link_name")
  private String linkName = null;

  @JsonProperty("link_href")
  private String linkHref = null;

  @JsonProperty("created_at")
  private String createdAt = null;

  @JsonProperty("orgid")
  private String orgid = null;

  @JsonProperty("force_canread")
  private String forceCanread = null;

  @JsonProperty("force_canwrite")
  private String forceCanwrite = null;

  @JsonProperty("do_force_canread")
  private Integer doForceCanread = null;

  @JsonProperty("do_force_canwrite")
  private Integer doForceCanwrite = null;

  @JsonProperty("visible")
  private Integer visible = null;

  @JsonProperty("announcement")
  private String announcement = null;

  /**
   * Do we send onboarding emails to new users?
   */
  public enum OnboardingEmailActiveEnum {
    NUMBER_0(0),
    NUMBER_1(1);

    private Integer value;

    OnboardingEmailActiveEnum(Integer value) {
      this.value = value;
    }
    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static OnboardingEmailActiveEnum fromValue(Integer input) {
      for (OnboardingEmailActiveEnum b : OnboardingEmailActiveEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("onboarding_email_active")
  private OnboardingEmailActiveEnum onboardingEmailActive = null;

  @JsonProperty("onboarding_email_body")
  private String onboardingEmailBody = null;

  @JsonProperty("onboarding_email_subject")
  private String onboardingEmailSubject = null;

  public Team id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Team name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Team commonTemplate(String commonTemplate) {
    this.commonTemplate = commonTemplate;
    return this;
  }

   /**
   * Get commonTemplate
   * @return commonTemplate
  **/
  @Schema(description = "")
  public String getCommonTemplate() {
    return commonTemplate;
  }

  public void setCommonTemplate(String commonTemplate) {
    this.commonTemplate = commonTemplate;
  }

  public Team commonTemplateMd(String commonTemplateMd) {
    this.commonTemplateMd = commonTemplateMd;
    return this;
  }

   /**
   * Get commonTemplateMd
   * @return commonTemplateMd
  **/
  @Schema(description = "")
  public String getCommonTemplateMd() {
    return commonTemplateMd;
  }

  public void setCommonTemplateMd(String commonTemplateMd) {
    this.commonTemplateMd = commonTemplateMd;
  }

  public Team userCreateTag(Integer userCreateTag) {
    this.userCreateTag = userCreateTag;
    return this;
  }

   /**
   * Get userCreateTag
   * @return userCreateTag
  **/
  @Schema(description = "")
  public Integer getUserCreateTag() {
    return userCreateTag;
  }

  public void setUserCreateTag(Integer userCreateTag) {
    this.userCreateTag = userCreateTag;
  }

  public Team forceExpTpl(Integer forceExpTpl) {
    this.forceExpTpl = forceExpTpl;
    return this;
  }

   /**
   * Get forceExpTpl
   * @return forceExpTpl
  **/
  @Schema(description = "")
  public Integer getForceExpTpl() {
    return forceExpTpl;
  }

  public void setForceExpTpl(Integer forceExpTpl) {
    this.forceExpTpl = forceExpTpl;
  }

  public Team linkName(String linkName) {
    this.linkName = linkName;
    return this;
  }

   /**
   * Get linkName
   * @return linkName
  **/
  @Schema(description = "")
  public String getLinkName() {
    return linkName;
  }

  public void setLinkName(String linkName) {
    this.linkName = linkName;
  }

  public Team linkHref(String linkHref) {
    this.linkHref = linkHref;
    return this;
  }

   /**
   * Get linkHref
   * @return linkHref
  **/
  @Schema(description = "")
  public String getLinkHref() {
    return linkHref;
  }

  public void setLinkHref(String linkHref) {
    this.linkHref = linkHref;
  }

  public Team createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public Team orgid(String orgid) {
    this.orgid = orgid;
    return this;
  }

   /**
   * Get orgid
   * @return orgid
  **/
  @Schema(description = "")
  public String getOrgid() {
    return orgid;
  }

  public void setOrgid(String orgid) {
    this.orgid = orgid;
  }

  public Team forceCanread(String forceCanread) {
    this.forceCanread = forceCanread;
    return this;
  }

   /**
   * Get forceCanread
   * @return forceCanread
  **/
  @Schema(description = "")
  public String getForceCanread() {
    return forceCanread;
  }

  public void setForceCanread(String forceCanread) {
    this.forceCanread = forceCanread;
  }

  public Team forceCanwrite(String forceCanwrite) {
    this.forceCanwrite = forceCanwrite;
    return this;
  }

   /**
   * Get forceCanwrite
   * @return forceCanwrite
  **/
  @Schema(description = "")
  public String getForceCanwrite() {
    return forceCanwrite;
  }

  public void setForceCanwrite(String forceCanwrite) {
    this.forceCanwrite = forceCanwrite;
  }

  public Team doForceCanread(Integer doForceCanread) {
    this.doForceCanread = doForceCanread;
    return this;
  }

   /**
   * Get doForceCanread
   * @return doForceCanread
  **/
  @Schema(description = "")
  public Integer getDoForceCanread() {
    return doForceCanread;
  }

  public void setDoForceCanread(Integer doForceCanread) {
    this.doForceCanread = doForceCanread;
  }

  public Team doForceCanwrite(Integer doForceCanwrite) {
    this.doForceCanwrite = doForceCanwrite;
    return this;
  }

   /**
   * Get doForceCanwrite
   * @return doForceCanwrite
  **/
  @Schema(description = "")
  public Integer getDoForceCanwrite() {
    return doForceCanwrite;
  }

  public void setDoForceCanwrite(Integer doForceCanwrite) {
    this.doForceCanwrite = doForceCanwrite;
  }

  public Team visible(Integer visible) {
    this.visible = visible;
    return this;
  }

   /**
   * Get visible
   * @return visible
  **/
  @Schema(description = "")
  public Integer getVisible() {
    return visible;
  }

  public void setVisible(Integer visible) {
    this.visible = visible;
  }

  public Team announcement(String announcement) {
    this.announcement = announcement;
    return this;
  }

   /**
   * Text shown on top of every page for all users of this team.
   * @return announcement
  **/
  @Schema(description = "Text shown on top of every page for all users of this team.")
  public String getAnnouncement() {
    return announcement;
  }

  public void setAnnouncement(String announcement) {
    this.announcement = announcement;
  }

  public Team onboardingEmailActive(OnboardingEmailActiveEnum onboardingEmailActive) {
    this.onboardingEmailActive = onboardingEmailActive;
    return this;
  }

   /**
   * Do we send onboarding emails to new users?
   * @return onboardingEmailActive
  **/
  @Schema(description = "Do we send onboarding emails to new users?")
  public OnboardingEmailActiveEnum getOnboardingEmailActive() {
    return onboardingEmailActive;
  }

  public void setOnboardingEmailActive(OnboardingEmailActiveEnum onboardingEmailActive) {
    this.onboardingEmailActive = onboardingEmailActive;
  }

  public Team onboardingEmailBody(String onboardingEmailBody) {
    this.onboardingEmailBody = onboardingEmailBody;
    return this;
  }

   /**
   * Get onboardingEmailBody
   * @return onboardingEmailBody
  **/
  @Schema(description = "")
  public String getOnboardingEmailBody() {
    return onboardingEmailBody;
  }

  public void setOnboardingEmailBody(String onboardingEmailBody) {
    this.onboardingEmailBody = onboardingEmailBody;
  }

  public Team onboardingEmailSubject(String onboardingEmailSubject) {
    this.onboardingEmailSubject = onboardingEmailSubject;
    return this;
  }

   /**
   * Get onboardingEmailSubject
   * @return onboardingEmailSubject
  **/
  @Schema(description = "")
  public String getOnboardingEmailSubject() {
    return onboardingEmailSubject;
  }

  public void setOnboardingEmailSubject(String onboardingEmailSubject) {
    this.onboardingEmailSubject = onboardingEmailSubject;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Team team = (Team) o;
    return Objects.equals(this.id, team.id) &&
        Objects.equals(this.name, team.name) &&
        Objects.equals(this.commonTemplate, team.commonTemplate) &&
        Objects.equals(this.commonTemplateMd, team.commonTemplateMd) &&
        Objects.equals(this.userCreateTag, team.userCreateTag) &&
        Objects.equals(this.forceExpTpl, team.forceExpTpl) &&
        Objects.equals(this.linkName, team.linkName) &&
        Objects.equals(this.linkHref, team.linkHref) &&
        Objects.equals(this.createdAt, team.createdAt) &&
        Objects.equals(this.orgid, team.orgid) &&
        Objects.equals(this.forceCanread, team.forceCanread) &&
        Objects.equals(this.forceCanwrite, team.forceCanwrite) &&
        Objects.equals(this.doForceCanread, team.doForceCanread) &&
        Objects.equals(this.doForceCanwrite, team.doForceCanwrite) &&
        Objects.equals(this.visible, team.visible) &&
        Objects.equals(this.announcement, team.announcement) &&
        Objects.equals(this.onboardingEmailActive, team.onboardingEmailActive) &&
        Objects.equals(this.onboardingEmailBody, team.onboardingEmailBody) &&
        Objects.equals(this.onboardingEmailSubject, team.onboardingEmailSubject);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, commonTemplate, commonTemplateMd, userCreateTag, forceExpTpl, linkName, linkHref, createdAt, orgid, forceCanread, forceCanwrite, doForceCanread, doForceCanwrite, visible, announcement, onboardingEmailActive, onboardingEmailBody, onboardingEmailSubject);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Team {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    commonTemplate: ").append(toIndentedString(commonTemplate)).append("\n");
    sb.append("    commonTemplateMd: ").append(toIndentedString(commonTemplateMd)).append("\n");
    sb.append("    userCreateTag: ").append(toIndentedString(userCreateTag)).append("\n");
    sb.append("    forceExpTpl: ").append(toIndentedString(forceExpTpl)).append("\n");
    sb.append("    linkName: ").append(toIndentedString(linkName)).append("\n");
    sb.append("    linkHref: ").append(toIndentedString(linkHref)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    orgid: ").append(toIndentedString(orgid)).append("\n");
    sb.append("    forceCanread: ").append(toIndentedString(forceCanread)).append("\n");
    sb.append("    forceCanwrite: ").append(toIndentedString(forceCanwrite)).append("\n");
    sb.append("    doForceCanread: ").append(toIndentedString(doForceCanread)).append("\n");
    sb.append("    doForceCanwrite: ").append(toIndentedString(doForceCanwrite)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    announcement: ").append(toIndentedString(announcement)).append("\n");
    sb.append("    onboardingEmailActive: ").append(toIndentedString(onboardingEmailActive)).append("\n");
    sb.append("    onboardingEmailBody: ").append(toIndentedString(onboardingEmailBody)).append("\n");
    sb.append("    onboardingEmailSubject: ").append(toIndentedString(onboardingEmailSubject)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
